spring:   
  datasource:
#    url: jdbc:mysql://192.168.1.123:3306/test
#    username: idsbase
#    password: idsbasemysql
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:D:/h5
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
#    schema: classpath:init.sql
  thymeleaf:
    prefix: classpath:/templates
    cache: false
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
server: 
    port: 8080